### ISSUE TITLE
Reusable workflows don't play nice with `merge_group` required checks

### ISSUE THREAD

**Issue by samuelburnham** [lurk-lab/ci-workflows#27]
## Background
We run a final set of required checks before merging PRs across `lurk-lab` repos, especially in https://github.com/lurk-lab/lurk-rs. These checks are often expensive in cost or runtime, so we set them to run once on the `merge_group` trigger when added to the merge queue.

While the PR is open, these checks are displayed as skipped and required: 
![Screenshot from 2024-01-16 12-03-42](https://github.com/lurk-lab/ci-workflows/assets/45365069/1bc3f70e-ea24-45ee-b759-0b73176c70b5)

but when added to the queue they run like any other CI check.

## Problem
When refactoring these checks to use reusable workflows, the existing required status check (which now calls the reusable workflow) shows as skipped before merge, but then doesn't appear to run when added to the queue:
![Screenshot from 2024-01-16 12-05-21](https://github.com/lurk-lab/ci-workflows/assets/45365069/705925cd-9c63-4bc0-a4c8-5eb8ec2a98d0)

If we change the required check to the reusable workflow directly, it does appear to run in the queue using the name of the reusable workflow (e.g. `Run tests on Linux-ARM`), but then the PR is blocked from merging with the same waiting message as above.

## Solution
Since the reusable workflow actually runs in the queue, this is the one we want to make required if possible. One solution lies in the conditional logic below:
```yml
on: 
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]
  merge_group:

jobs:
  job-name:
    name: Status check name
    # This conditional will skip the `pull_request` trigger and run on `merge_group`
    if: github.event_name != 'pull_request' || github.event.action == 'enqueued'
```
If we move this `if` statement from the top-level workflow to the reusable workflow itself, it will skip the latter's required status check and un-block the PR accordingly while still running on `merge_group` as before.

This does constrain downstream users to only running on `merge_group`, but for Lurk Lab repos this is our main use case anyway (apart from the occasional need for manual `workflow_dispatch` triggers, which can be handled on a case-by-case basis).
